
root: "/home/roit/aws/aprojects/scenario"

dump_path: "/home/roit/datasets/cesiumData/40-40-0-15-53-4isl"

start_time: "2000-01-01T00:00:00Z"
end_time: "2000-01-02T00:00:00Z"
num_ISLs: 4
constellation:

  name: "lite"
  num_orbits: 40
  num_sats_per_orbit: 40
  phase_factor: 0
  eccentricity: 0.0000001
#seed satellite
satellite:
  mean_motion_rev_per_day: 15.2202
  inclination_degree: 53
  perigee_degree: 268.4266
  mean_anomaly_degree: 91.5750
  raan: 0
GSL:
  multiThreading: true
  input_item_len: 30

GSs_path: "cities.txt"


