
root: "/home/roit/aws/aprojects/scenario"

dump_path: "/home/roit/datasets/cesiumData/20-20-0-15-53-4isl"

start_time: "2000-01-01T00:00:00Z"
end_time: "2000-01-02T00:00:00Z"

constellation:

  name: "lite"
  num_orbits: 20
  num_sats_per_orbit: 20
  phase_factor: 0
  eccentricity: 0.0000001
#seed satellite
satellite:
  mean_motion_rev_per_day: 15.2202
  inclination_degree: 53
  perigee_degree: 268.4266
  mean_anomaly_degree: 91.5750
  raan: 0

ISL:
  intral_link_deltas: [-1,1] #don't change
  inter_link_deltas: [0] #4isls
#  inter_link_deltas: [0,1] #6isls
#  inter_link_deltas: [0,-1]

GSL:
  multiThreading: true
  input_item_len: 30

GSs_path: "cities.txt"


ACs_path: "aerocrafts.json"