

dump_path: "/home/roit/datasets/cesiumData/3-3"

start_time: [2000,1,1]
end_time: [2000,1,2]

constellation:

  name: "lite"
  num_orbits: 12
  num_sats_per_orbit: 12
  inclination_degree: 53
  phase_diff: true
  eccentricity: 0.0000001
  arg_of_perigee_degree: 0.0
  mean_motion_rev_per_day: 13.66



