
root: "/home/roit/aws/aprojects/constellation"

dump_path: "/home/roit/datasets/cesiumData/20-20-0-15-53-4isl"

start_time: [2000,1,1]
end_time: [2000,1,2]
num_ISLs: 4
constellation:

  name: "lite"
  num_orbits: 20
  num_sats_per_orbit: 20
  phase_factor: 0
  eccentricity: 0.0000001
#seed satellite
satellite:
  mean_motion_rev_per_day: 15.2202
  inclination_degree: 53
  perigee_degree: 268.4266
  mean_anomaly_degree: 91.5750
  raan: 0
GSL:
  multiThreading: true
  input_item_len: 30

GSs_path: "cities.txt"


